fixed setup file
palmetto/palm-cli pull request #48
Opened 2021-12-03 17:40 UTC by norton120

## Pull request checklist

Before submitting your PR, please review the following checklist:

- [x] Consider adding a unit test if your PR resolves an issue.
- [x] All new and existing tests pass locally (`palm test`)
- [x] Lint (`palm lint`) has passed locally and any fixes were made for failures
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)

### Breaking changes

- [ ] Check if this pull request introduces a breaking change

## What does this implement/fix? Explain your changes.
If you try to scaffold a new plugin it will fail, looking for a setup template that is not named to match the actual template. 
This fixes that.

2021-12-03 20:58 UTC, jakeberesford-palmetto commented on palm/cli.py
> +        ("docker ps", "Docker is not running, please start it first",),
I agree this looks better... but `black` does not. Linting ablaze with this change

2021-12-03 20:59 UTC, jakeberesford-palmetto requested changes
Thanks for fixing the issue, unfortunately your test doesn't pass

2021-12-03 22:57 UTC, norton120 commented
blech; I think I may have accidentally finished these fixes on my fork's develop. will update and push now

2021-12-04 01:50 UTC, jakeberesford-palmetto approved these changes
Thanks for fixing!

2021-12-06 15:33 UTC, emekdahl-palmetto approved these changes

2021-12-08 15:51 UTC, merged