Update Install With Generic Drop-In Instructions
palmetto/palm-cli pull request #95
Opened 2022-12-30 14:07 UTC by norton120

This makes the "add to path" command drop-and-go for mac/nix users 🚀

- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)

### Breaking changes

- [ ] Check if this pull request introduces a breaking change
nope no breaking stuff

## What does this implement/fix? Explain your changes.

This makes the "add to path" section of the docs a bit more agnostic - uses whatever python3 version is the current system default, and covers all 3 popular shells.

## Does this close any currently open issues?
nope I don't think so

## Any other comments?
This still doesn't help windoze folks, probably need to add that as well at some point to make the install docs super helpful.

## Where has this been tested?

**Operating System:** Mac OS (M1) Ventura 13.1 (22C65)

**Platform:** Bash shell

**Target Platform:** Bash, Zsh, Fsh

2023-01-03 15:53 UTC, jakeberesford-palmetto commented on docs/source/usage.rst
> +``export PALM_INSTALL_LIB_AT=$(python3 --version | sed -e "s/\(Python 3\.\)\([0-9]\)\.\([0-9]\)/3.\2/") && echo "\nexport PATH=$PATH:$HOME/Library/Python/${PALM_INSTALL_LIB_AT}/bin\n" | tee -a ~/.zpr
The sed command here does not work for patch versions > 9. e.g. running python 3.9.13 the result is `3.93`

2023-01-05 14:20 UTC, jakeberesford-palmetto requested changes
This will be a nice improvement, but it needs to work for all python versions.

2023-03-02 14:23 UTC, jakeberesford-palmetto commented
@norton120 - any plans to update the sed command? I don't have bandwidth to help with this right now.

2023-03-02 14:24 UTC, norton120 commented
Ah man sorry I thought I did already, will definitely do so

2023-10-03 14:14 UTC, jakeberesford-palmetto approved these changes

2023-10-03 14:14 UTC, merged